# This is a basic workflow to help you get started with Actions

name: Run k6

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "loadtest"
  loadtest:
    name: k6 local test run 
    runs-on: ubuntu-latest
    container: docker://loadimpact/k6:0.34.1

    steps:

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Run k6 local test
      uses: k6io/action@v0.1
      with:
        filename: yaru.js
